import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

// Configure Inter font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Regular, Medium, Bold
});

// Configure Roboto font
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Regular, Medium, Bold
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable} antialiased`}>
        <div>
          <Navbar />
          <main className="">{children}</main>
        </div>
      </body>
    </html>
  );
}
